CC := gcc
CFLAGS := -W -Wall -pedantic -lm

all:

	$(CC) buscador.c -o buscador $(CFLAGS)

run:

	./buscador /home/admin-lart/Documentos/FSO/SO_Trabalhos/T4/q02/archieves test 4

clean:

	rm -rf buscador
